name: 'docker build and push'

on:
  workflow_call:
    inputs:
      push:
        default: true
        required: false
        type: bool
      tags:
        required: true
        type: string

jobs:
  docker:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
