name: 'docker build and push'

on:
  workflow_call:
    inputs:
      push:
        default: false
        required: false
        type: boolean
      tags:
        required: false
        type: string
        default: |
          type=raw,enable=${{ github.ref == format('refs/heads/{0}', 'development') }},priority=200,prefix=,suffix=,value=latest
          type=raw,enable=${{ github.ref == format('refs/heads/{0}', 'master') }},priority=200,prefix=,suffix=,value=stable
          type=ref,event=tag
          type=ref,suffix=-{{sha}},event=branch
          type=ref,suffix=-{{sha}},event=pr
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{version}}
          type=sha
      images:
        required: true
        type: string
    secrets:
      host:
        required: false
      user:
        required: false
      pass:
        required: false

jobs:
  docker:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: ${{ inputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        if: inputs.push
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.host != '' && secrets.host || secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.user != '' && secrets.user || secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.pass != '' && secrets.pass || secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
