name: 'SemVer'

on:
  workflow_call:
    secrets:
      github-token:
        description: 'A github token passed from the caller workflow'
        required: true
      npm-token:
        description: 'A npm token passed from the caller workflow'
        required: false
  push:
    branches:
      - master
      - development

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/github
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          NPM_TOKEN: ${{ secrets.npm-token }}
        run: npx semantic-release
