name: 'SemVer'

on:
  workflow_call:
    secrets:
      token:
        required: false

  push:
    branches:
      - master
      - development

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/github @semantic-release/git
      - name: Release self
        if: github.event_name == 'push'
        run: npx semantic-release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: github.event_name == 'workflow_call'
        run: npx semantic-release
        env:
          CI: true
          GH_TOKEN: ${{ inputs.token }}
          GITHUB_TOKEN: ${{ inputs.token }}
